{
 "title": "Lituya Status",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Fwd Cabin",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Fwd Cabin Temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "environment.inside.lituyamon.temperature",
     "query": "SELECT (9/5)*(value-273.15)+32 FROM \"one_year\".\"environment.inside.fwdcabin.temperature\" WHERE $timeFilter\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pilot",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Pilot Temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "environment.inside.lituyamon.temperature",
     "query": "SELECT (9/5)*(value-273.15)+32 FROM \"one_year\".\"environment.inside.pilot.temperature\" WHERE $timeFilter\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Lazarette",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Aft Cabin Temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "environment.inside.lituyamon.temperature",
     "query": "SELECT (9/5)*(value-273.15)+32 FROM \"one_year\".\"environment.inside.lazarette.temperature\" WHERE $timeFilter\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Engine Room",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Engine Room Temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "environment.inside.lituyamon.temperature",
     "query": "SELECT (9/5)*(value-273.15)+32 FROM \"one_year\".\"environment.inside.engineroom.temperature\" WHERE $timeFilter\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "alertlist",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "fahrenheit" }
   ],
   "targets": [
    {
     "alias": "Pilot",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "environment.inside.lituyamon.temperature",
     "query": "SELECT (9/5)*(value-273.15)+32 FROM \"one_year\".\"environment.inside.pilot.temperature\" WHERE $timeFilter\n ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Fwd Cabin",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "environment.inside.lituyamon.temperature",
     "query": "SELECT (9/5)*(value-273.15)+32 FROM \"one_year\".\"environment.inside.fwdcabin.temperature\" WHERE $timeFilter\n ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Engine Room",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "environment.inside.lituyamon.temperature",
     "query": "SELECT (9/5)*(value-273.15)+32 FROM \"one_year\".\"environment.inside.engineroom.temperature\" WHERE $timeFilter\n ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Lazarette",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "environment.inside.lituyamon.temperature",
     "query": "SELECT (9/5)*(value-273.15)+32 FROM \"one_year\".\"environment.inside.lazarette.temperature\" WHERE $timeFilter\n ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "House Battery",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Engine Temperature",
     "measurement": "environment.inside.lituyamon.temperature",
     "query": "SELECT moving_average(value, 10)  FROM \"one_year\".\"electrical.batteries.house.voltage\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "House Battery",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 12 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "alias": "House Battery Voltage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "environment.inside.lituyamon.temperature",
     "query": "SELECT moving_average(value, 10) FROM \"one_year\".\"electrical.batteries.house.voltage\" WHERE $timeFilter\n ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Engine Temperature",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Engine Temperature",
     "measurement": "environment.inside.lituyamon.temperature",
     "query": "SELECT (9/5)*(value-273.15)+32  FROM \"one_year\".\"propulsion.qsc83.temperature\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Engine Temperature",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 13, "y": 12 },
   "yaxes": [
    { "format": "fahrenheit" }
   ],
   "targets": [
    {
     "alias": "Engine Temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "environment.inside.lituyamon.temperature",
     "query": "SELECT (9/5)*(value-273.15)+32 FROM \"one_year\".\"propulsion.qsc83.temperature\" WHERE $timeFilter\n ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "CPU Temperature",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "LituyaMon Temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "environment.inside.lituyamon.temperature",
     "query": "SELECT (9/5)*(value-273.15)+32 FROM \"one_year\".\"environment.inside.lituyamon.temperature\" WHERE $timeFilter\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Temperature",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 13, "y": 18 },
   "yaxes": [
    { "format": "fahrenheit" }
   ],
   "targets": [
    {
     "alias": "LituyaMon Temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "environment.inside.lituyamon.temperature",
     "query": "SELECT (9/5)*(value-273.15)+32 FROM \"one_year\".\"environment.inside.lituyamon.temperature\" WHERE $timeFilter\n ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true
  },
  {
   "title": "Salon Humidity",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Humidity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "environment.inside.lituyamon.temperature",
     "query": "SELECT value FROM \"one_year\".\"environment.inside.salon.humidity\" WHERE $timeFilter\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "ER Humidity",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Humidity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "environment.inside.lituyamon.temperature",
     "query": "SELECT value FROM \"one_year\".\"environment.inside.engineroom.humidity\" WHERE $timeFilter\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}